version: '3.8'
services:
  spring-boot-app:
    build:
      context: ./
    image: spring-boot-app-image
    ports:
      - "8080:8080"
    depends_on:
      - tts-service

  tts-service:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.2  # Image của dịch vụ TTS
    ports:
      - "8880:8880"
    networks:
      - tts-network  # Đảm bảo tất cả các dịch vụ trong cùng một mạng

networks:
  tts-network:
    driver: bridge
